"""add owner_id to course

Revision ID: 14a58a591f64
Revises: cbd2fad0ff5e
Create Date: 2025-11-19 15:10:02.352926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a58a591f64'
down_revision: Union[str, None] = 'cbd2fad0ff5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) сначала добавляем nullable=True
    op.add_column(
        "courses",
        sa.Column("owner_id", sa.Integer(), nullable=True),
    )

    # 2) если у тебя уже есть какой-то преподаватель, можно
    # проставить его id всем существующим курсам.
    # Например, пусть это user_id = 1:
    op.execute(
        """
        UPDATE courses
        SET owner_id = 4
        """
    )

    # 3) теперь делаем поле NOT NULL
    op.alter_column("courses", "owner_id", nullable=False)

    # 4) и добавляем внешний ключ (если его ещё нет)
    op.create_foreign_key(
        "fk_courses_owner_id_users",
        "courses",
        "users",
        ["owner_id"],
        ["id"],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='unique')
    op.create_index('ix_courses_title', 'courses', ['title'], unique=True)
    op.drop_column('courses', 'owner_id')
    # ### end Alembic commands ###
