"""add lesson/task completions

Revision ID: cbd2fad0ff5e
Revises: 
Create Date: 2025-11-19 14:40:27.673108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd2fad0ff5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('progress_user_id_fkey', 'progress', type_='foreignkey')
    op.drop_constraint('progress_course_id_fkey', 'progress', type_='foreignkey')
    op.create_foreign_key(None, 'progress', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'progress', 'users', ['user_id'], ['id'])
    op.drop_column('progress', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_foreign_key('progress_course_id_fkey', 'progress', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('progress_user_id_fkey', 'progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
